name: Test
on:
  push:
    branches: ["main"]
  pull_request_target:

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          apt: gcc libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Run tests
        run: go test -v -tags headless -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
